### ISSUE TITLE
Error: The method 'RaisedButton' isn't defined for the class '_DemoState'.

### ISSUE THREAD

**Issue by nelsonic** [perclasson/flutter_code#1]
Hi @perclasson 👋 
Read your post on https://medium.com/flutter/optimizing-performance-in-flutter-web-apps-with-tree-shaking-and-deferred-loading-535fbe3cd674 Thanks! 🙏 

Executed the following commands: 💻 

```sh
git clone git@github.com:perclasson/flutter_code.git
cd flutter_code/deferred_loading
flutter run --release -d chrome
```

Got the following output:

```sh
Running "flutter pub get" in deferred_loading...
Resolving dependencies... (22.3s)
+ async 2.10.0
+ boolean_selector 2.1.1
+ characters 1.2.1 (1.3.0 available)
+ clock 1.1.1
+ collection 1.17.0 (1.17.1 available)
+ cupertino_icons 0.1.3 (1.0.5 available)
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_test 0.0.0 from sdk flutter
+ js 0.6.5 (0.6.7 available)
+ matcher 0.12.13 (0.12.14 available)
+ material_color_utilities 0.2.0
+ meta 1.8.0 (1.9.0 available)
+ path 1.8.2 (1.8.3 available)
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.1
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test_api 0.4.16 (0.4.18 available)
+ vector_math 2.1.4
Changed 22 dependencies!
Launching lib/main.dart on Chrome in release mode...
Upgrading .gitignore
Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
lib/main.dart:50:13:
Error: The method 'RaisedButton' isn't defined for the class '_DemoState'.
 - '_DemoState' is from 'package:deferred_loading/main.dart' ('lib/main.dart').
            RaisedButton(
            ^^^^^^^^^^^^
lib/main.dart:59:13:
Error: The method 'RaisedButton' isn't defined for the class '_DemoState'.
 - '_DemoState' is from 'package:deferred_loading/main.dart' ('lib/main.dart').
            RaisedButton(
            ^^^^^^^^^^^^
Error: Compilation failed.


#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:293:11)
<asynchronous suspension>
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                              5.3s
Exception: Failed to compile application for the Web.
```
 
Opening this issue to inform both your fine self and anyone `else` viewing this repo in the future. 💭 

Very happy to PR and update if you want to update the project. 🧑‍💻 
But won't if you're too busy to review/merge it. ⏳

**Comment by perclasson** [comment]
Thank you for creating the issue. Seems like RaisedButton is deprecated and it should be ElevatedButton now. Let me merge in a fix. :)
